<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

/** Absolute path to the webroot. */
if ( ! defined( 'ABSPATH' ) ) {
	define('ABSPATH', __DIR__ . '/');
}

/** Location of your WordPress configuration. */
require_once( dirname( __DIR__ ) . '/config/wp-config.php' );
require_once( ABSPATH . 'wp-settings.php' );
